import Head from 'next/head'
import dynamic from 'next/dynamic'

// @ts-ignore
const App = dynamic(() => import('../components/App').then((mod) => mod.App), {
  ssr: false,
})

export default function Home() {
  return (
    <>
      <Head>
        <title>ZNP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <App />
      </main>
    </>
  )
}
